-- Criar novo BD

CREATE DATABASE GREENHOUSE;

-- Utilizando o banco de dados

USE GREENHOUSE;

-- Criando uma tabela
CREATE TABLE `GREENHOUSE`.`PLANTS` (
	`PLANT_NAME` CHAR(30) NOT NULL,
    `SENSOR_VALUE` FLOAT DEFAULT NULL,
    `SENSOR_EVENT` TIMESTAMP NOT NULL
		DEFAULT CURRENT_TIMESTAMP ON
        UPDATE CURRENT_TIMESTAMP,
	`SENSOR_LEVEL` CHAR(5) DEFAULT NULL,
    PRIMARY KEY `PK_PLANT_NAME` (`PLANT_NAME`)
);

-- COMANDOS DML DE INSERÇÃO DE DADOS
INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES('Orquidea', 80, 'HIGH');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES('Samambaia', 60, 'LOW');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES('Babosa', 50, 'MED');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES('Rosa', 5, 'HIGH');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES('Sempre-verde', 200, 'LOW');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES('Maracujá', 2, 'MED');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES('BANANA', 20, 'HIGH');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES('MILHO', 100, 'LOW');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES('CENOURA', 1, 'MED');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES('Mandioca', 51, 'LOW');

-- EXECUTANDO COMANDOS DQL - SELECT
-- consultando tudo da tabela
SELECT * FROM `GREENHOUSE`.`PLANTS`;

-- ESPECIFICANDO COLUNAS DESEJADAS
SELECT `PLANT_NAME`, `SENSOR_EVENT`
FROM `GREENHOUSE`.`PLANTS`;

-- APLICAR FILTROS NOS REGISTROS DE DADOS
SELECT * FROM PLANTS WHERE SENSOR_LEVEL = 'HIGH'
AND SENSOR_VALUE >= 1 AND SENSOR_VALUE <= 20;

SELECT * FROM PLANTS WHERE  SENSOR_LEVEL IN ('HIGH' , 'LOW');

-- CLAUSULA DE ORDENAÇÃO
SELECT * FROM PLANTS WHERE SENSOR_VALUE > 420 ORDER BY SENSOR_VALUE DESC;

-- FUNÇÕES DE AGRUPAMENTO
SELECT COUNT(*), SENSOR_LEVEL FROM PLANTS GROUP BY SENSOR_LEVEL;

-- EXERCICIO

	-- Select top
SELECT PLANT_NAME FROM PLANTS WHERE SENSOR_LEVEL = 'MED' LIMIT 3;

	-- Mind and Max
SELECT MIN(20) FROM PLANTS;
SELECT MAX(200) FROM PLANTS;
SELECT MIN(`SENSOR_VALUE`) FROM `PLANTS`; 

	-- SUM
SELECT SUM(`SENSOR_VALUE`) FROM `PLANTS`; 

	-- AVG
SELECT AVG(`SENSOR_VALUE`) FROM `PLANTS`; 

	-- LIKE

-- Comando UPDATE PARA ATUALIZAR REGISTROS DE DADOS

SELECT * FROM PLANTS;

UPDATE PLANTS
SET SENSOR_VALUE = 90, SENSOR_LEVEL = 'HIGH'
WHERE PLANT_NAME = 'Babosa';

-- Apagando registros da tabela do BD

DELETE FROM PLANTS
WHERE PLANT_NAME = 'BANANA';