-- Excluindo o BD
-- DROP DATABASE `BD2401`; 

-- Criando o Schema do BD
CREATE SCHEMA `BD2401`;

-- Criando a Tabela
CREATE TABLE `BD2401`.`NEW_TABLE` (
	`ID_MEMBER`INT NOT NULL AUTO_INCREMENT,
    `FIRST_NAME` VARCHAR(20) NOT NULL,
    `ACTIVE` BIT(1) NULL  DEFAULT 1,
    `WHEN_ADDED` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    `LAST_MODIFIED` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID_MEMBER`)
    
);

-- Inserindo dados na tabela
INSERT INTO `BD2401`.`NEW_TABLE` (`FIRST_NAME`)
VALUES ('Alex Kophal Knecht');

INSERT INTO `BD2401`.`NEW_TABLE` (`FIRST_NAME`, `ACTIVE`)
VALUES ('Selina Kophal Knecht', 0);

INSERT INTO `BD2401`.`NEW_TABLE` (`FIRST_NAME`, `ACTIVE`)
VALUES ('Lourdes k Knecht',0);

-- EXIBINDO/CONSULTANDO DADOS

SELECT * FROM `BD2401`.`NEW__TABLE`;